# Generated by Django 3.1.5 on 2021-01-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomaker', '0003_auto_20210126_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(default='2021-01-26 00:14:51'),
        ),
    ]
