# Generated by Django 3.1.5 on 2021-01-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomaker', '0004_auto_20210126_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(default='2021-01-26 01:10:35'),
        ),
    ]
