# Generated by Django 3.1.5 on 2021-01-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomaker', '0005_auto_20210126_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(default='2021-01-26 01:30:57'),
        ),
    ]
